---
title: "Album Genre Scraping - AOTY.org"
author: "Zander Meitus"
date: "January 19, 2019"
output: html_document
---
## Overview
This script is designed to scrape all the genre tags for each album. These tags will be used for additional analyses.


## Libraries
```{r, message=FALSE, echo=FALSE}
library(rvest)
library(dplyr)
library(tidyr)
library(stringr)
library(igraph)
library(visNetwork)

```

## Functions
```{r}
source('./functions/cleanCriticScore.R')
```

##Scrape all genres from 2018
```{r, cache = T}
pages <- 1
years <- c(2019)


# loop for each year
for (y in years){
        tagsList <- list()
        albumList<- list()
        
        # loop of urls for each page of 25 albums 
        for(i in pages){
                #make vector of album page urls
                url <- paste0("https://www.albumoftheyear.org/ratings/6-highest-rated/",y,"/",i)
                
                html <- read_html(url)
                
                # store artist, album, and ranks
                albumList[[i]] <- html %>% html_nodes('.albumListRow')%>% 
                        html_text () %>%
                        data.frame()
                
                # store urls for tags loops
                album.urls <- html %>% 
                        html_nodes(".albumListTitle a") %>% 
                        html_attr('href')
                
                #scrape genre from each url
                list <- list()
                z<-1
                for(u in album.urls){
                        url.a <- paste("https://www.albumoftheyear.org",u,sep = "")
                        html <- read_html(url.a)
                        list[[z]] <- html %>% 
                                html_nodes(".tag") %>% 
                                html_text()
                        z<- z+1
                }
                
                # combine vectors into a dataframe
                tags<-as.data.frame(
                        t(
                                as.matrix(sapply(list, '[', seq(max(sapply(list, length))))
                                          )
                                )
                        )
                
                # set parameters for id
                a <- ((i-1)*25)+1
                b <- a + dim(tags)[1]-1
                
                # create id so they can be ordered properly for combination
                tags$id <- a:b
                        
                tagsList[[i]] <- tags 
        }
        
        
        # set what names should be
        full.names <- c('V1','V2','V3','V4','V5','V6','V7','id')
        
        # separate into lists of proper length and too short
        tagsListGood <- tagsList[sapply(tagsList,function(x) ncol(x) ==length(full.names))]
        
        tagsListBad <- tagsList[sapply(tagsList,function(x) ncol(x) != length(full.names))]
        

        
        # add missing columns to bad tag lists
        redeemed.list <- list()
        if(length(tagsListBad >0)){
                
                for(b in length(tagsListBad)){
                        
                        df <- tagsListBad[b][[1]]
                        
                        # identify missing columns
                        missing.names <- setdiff(full.names,names(df))
                        
                        # create missing variables
                        missingVars <-data.frame(
                                matrix(
                                        rep(NA,
                                            dim(df)[1]*length(missing.names)
                                            ),
                                        dim(df)[1]
                                        )
                                )
                        
                         colnames(missingVars) <- missing.names
                         
                         dfFull <- cbind(df,missingVars)
                         
                         redeemed.list[[b]] <-dfFull
                }
        
        }
        
        # make into dataframes
        tagsDfGood <- do.call(rbind,tagsListGood)
        tagsDfRedeem <- do.call(rbind, redeemed.list)
        
        # combine tag dataframes
        tagsDfFull <- rbind(tagsDfGood,tagsDfRedeem) %>%
                arrange(id)
        
        # combine album dataframes
        albumDfRaw <- do.call(rbind, albumList)
        
        # clean album dataframes
        albumDfClean <- cleanCriticScore(albumDfRaw)
        
        # rename columns
        colnames(tagsDfFull) = c("tag1","tag2","tag3","tag4","tag5","tag6","tag7","id")
        
        # combine album info with genre tags
        final <- cbind(albumDfClean,tagsDfFull)
        # saveout dataframe
        # saveRDS(tagsDfFull,paste0('aotyGenreTags',y,'.Rds'))
}
```

##Process scraped genres
```{r}
# get all combinations of two genres on same album
outlist <- list() 

for(i in 1:nrow(tagsDfFull)){
        
        x <- as.character(unlist(tagsDfFull[i,])) 
        xCombo <- data.frame(t(combn(x,2)))
        outlist[[i]] <- xCombo
}
 
tagCombosRaw <- do.call(rbind,outlist)

colnames(tagCombosRaw) <- c('tag1','tag2')
tagCombosClean1 <- tagCombosRaw %>% filter(complete.cases(.),
                                  tag1 != ' Add Tag' & tag2 != ' Add Tag',
                                  tag1 != ' More' & tag2 != ' More')

recordIndex <- c(grep("record", tagCombosClean1$tag1),
                 grep("record", tagCombosClean1$tag2))


tagCombosClean <- tagCombosClean1[-recordIndex,]
# tagCombos<- tagCombos[1:500,]
saveRDS()
```

## Plot graph
```{r}
g <- graph_from_data_frame(tagCombosClean, directed=F)

cluster <- cluster_louvain(g)

# plot(g)

# visNetwork
nodes <- data.frame(
        id = unique(
                c(unique(as.character(tagCombosClean$tag1)),
                unique(as.character(tagCombosClean$tag2)))
                ),
        label = unique(
                c(unique(as.character(tagCombosClean$tag1)),
                unique(as.character(tagCombosClean$tag2)))
                )
        )

edges <- tagCombosClean
colnames(edges) <- c('from','to')

# plot the graph
visNetwork(nodes,edges) %>%
        visPhysics(maxVelocity = 1) %>%
        visClusteringByColor(colors = 'blue')
```

## Clean genre tags

```{r}
tags2 <- data.frame(sapply(tags, as.character))
g <- function(x){
        x2<- as.character(tags$v5)
        i<-grep("perfect rating",x2)
        x2[i]<- ""
}

tags2<- data.frame(sapply(tags, g))
```
